import UserProvider from "@/context/UserProvider";
import "./globals.css";
import { Inter, Roboto_Slab } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className} ${robotoSlab.variable}`}>
        <div className="flex flex-1">
          <UserProvider>{children}</UserProvider>
        </div>
      </body>
    </html>
  );
}
